// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nrpc.proto

/*
Package nrpc is a generated protocol buffer package.

It is generated from these files:
	nrpc.proto

It has these top-level messages:
	Error
	Void
	NoRequest
	NoReply
*/
package nrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubjectRule int32

const (
	SubjectRule_COPY    SubjectRule = 0
	SubjectRule_TOLOWER SubjectRule = 1
)

var SubjectRule_name = map[int32]string{
	0: "COPY",
	1: "TOLOWER",
}
var SubjectRule_value = map[string]int32{
	"COPY":    0,
	"TOLOWER": 1,
}

func (x SubjectRule) String() string {
	return proto.EnumName(SubjectRule_name, int32(x))
}
func (SubjectRule) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Error_Type int32

const (
	Error_CLIENT Error_Type = 0
	Error_SERVER Error_Type = 1
	Error_EOS    Error_Type = 3
)

var Error_Type_name = map[int32]string{
	0: "CLIENT",
	1: "SERVER",
	3: "EOS",
}
var Error_Type_value = map[string]int32{
	"CLIENT": 0,
	"SERVER": 1,
	"EOS":    3,
}

func (x Error_Type) String() string {
	return proto.EnumName(Error_Type_name, int32(x))
}
func (Error_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Error struct {
	Type     Error_Type `protobuf:"varint,1,opt,name=type,enum=nrpc.Error_Type" json:"type,omitempty"`
	Message  string     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	MsgCount uint32     `protobuf:"varint,3,opt,name=msgCount" json:"msgCount,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetType() Error_Type {
	if m != nil {
		return m.Type
	}
	return Error_CLIENT
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetMsgCount() uint32 {
	if m != nil {
		return m.MsgCount
	}
	return 0
}

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NoRequest struct {
}

func (m *NoRequest) Reset()                    { *m = NoRequest{} }
func (m *NoRequest) String() string            { return proto.CompactTextString(m) }
func (*NoRequest) ProtoMessage()               {}
func (*NoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NoReply struct {
}

func (m *NoReply) Reset()                    { *m = NoReply{} }
func (m *NoReply) String() string            { return proto.CompactTextString(m) }
func (*NoReply) ProtoMessage()               {}
func (*NoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

var E_PackageSubject = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50000,
	Name:          "nrpc.packageSubject",
	Tag:           "bytes,50000,opt,name=packageSubject",
	Filename:      "nrpc.proto",
}

var E_PackageSubjectParams = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: ([]string)(nil),
	Field:         50001,
	Name:          "nrpc.packageSubjectParams",
	Tag:           "bytes,50001,rep,name=packageSubjectParams",
	Filename:      "nrpc.proto",
}

var E_ServiceSubjectRule = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*SubjectRule)(nil),
	Field:         50002,
	Name:          "nrpc.serviceSubjectRule",
	Tag:           "varint,50002,opt,name=serviceSubjectRule,enum=nrpc.SubjectRule",
	Filename:      "nrpc.proto",
}

var E_MethodSubjectRule = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*SubjectRule)(nil),
	Field:         50003,
	Name:          "nrpc.methodSubjectRule",
	Tag:           "varint,50003,opt,name=methodSubjectRule,enum=nrpc.SubjectRule",
	Filename:      "nrpc.proto",
}

var E_ServiceSubject = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51000,
	Name:          "nrpc.serviceSubject",
	Tag:           "bytes,51000,opt,name=serviceSubject",
	Filename:      "nrpc.proto",
}

var E_ServiceSubjectParams = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: ([]string)(nil),
	Field:         51001,
	Name:          "nrpc.serviceSubjectParams",
	Tag:           "bytes,51001,rep,name=serviceSubjectParams",
	Filename:      "nrpc.proto",
}

var E_MethodSubject = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         52000,
	Name:          "nrpc.methodSubject",
	Tag:           "bytes,52000,opt,name=methodSubject",
	Filename:      "nrpc.proto",
}

var E_MethodSubjectParams = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: ([]string)(nil),
	Field:         52001,
	Name:          "nrpc.methodSubjectParams",
	Tag:           "bytes,52001,rep,name=methodSubjectParams",
	Filename:      "nrpc.proto",
}

var E_StreamedReply = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         52002,
	Name:          "nrpc.streamedReply",
	Tag:           "varint,52002,opt,name=streamedReply",
	Filename:      "nrpc.proto",
}

func init() {
	proto.RegisterType((*Error)(nil), "nrpc.Error")
	proto.RegisterType((*Void)(nil), "nrpc.Void")
	proto.RegisterType((*NoRequest)(nil), "nrpc.NoRequest")
	proto.RegisterType((*NoReply)(nil), "nrpc.NoReply")
	proto.RegisterEnum("nrpc.SubjectRule", SubjectRule_name, SubjectRule_value)
	proto.RegisterEnum("nrpc.Error_Type", Error_Type_name, Error_Type_value)
	proto.RegisterExtension(E_PackageSubject)
	proto.RegisterExtension(E_PackageSubjectParams)
	proto.RegisterExtension(E_ServiceSubjectRule)
	proto.RegisterExtension(E_MethodSubjectRule)
	proto.RegisterExtension(E_ServiceSubject)
	proto.RegisterExtension(E_ServiceSubjectParams)
	proto.RegisterExtension(E_MethodSubject)
	proto.RegisterExtension(E_MethodSubjectParams)
	proto.RegisterExtension(E_StreamedReply)
}

func init() { proto.RegisterFile("nrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x6b, 0x6c, 0x72, 0x39, 0x51, 0x23, 0x77, 0xe8, 0xc2, 0x14, 0x04, 0x96, 0x55, 0x89,
	0x88, 0x85, 0x23, 0x95, 0x9d, 0x97, 0x44, 0x8e, 0x54, 0xa9, 0xd4, 0xd5, 0x24, 0x14, 0xc1, 0x06,
	0x39, 0xf6, 0xe0, 0x1a, 0xec, 0xcc, 0x30, 0x33, 0x46, 0xca, 0x0b, 0x74, 0x85, 0xba, 0xec, 0x1a,
	0x78, 0x0a, 0x78, 0x0b, 0x2e, 0x2f, 0x84, 0x3c, 0x76, 0x50, 0x4c, 0x02, 0xe9, 0x6e, 0xce, 0xe5,
	0xff, 0xce, 0x3f, 0x67, 0x06, 0x60, 0xce, 0x59, 0xe4, 0x32, 0x4e, 0x25, 0x45, 0x46, 0x79, 0x3e,
	0xb0, 0x13, 0x4a, 0x93, 0x8c, 0x0c, 0x55, 0x6e, 0x56, 0xbc, 0x19, 0xc6, 0x44, 0x44, 0x3c, 0x65,
	0x92, 0xf2, 0xaa, 0xcf, 0xf9, 0xa8, 0xc1, 0x6d, 0x9f, 0x73, 0xca, 0xd1, 0x21, 0x18, 0x72, 0xc1,
	0x88, 0xa5, 0xd9, 0xda, 0xa0, 0x7f, 0x64, 0xba, 0x0a, 0xa6, 0x4a, 0xee, 0x74, 0xc1, 0x08, 0x56,
	0x55, 0x64, 0x41, 0x3b, 0x27, 0x42, 0x84, 0x09, 0xb1, 0x6e, 0xd9, 0xda, 0xa0, 0x8b, 0x97, 0x21,
	0x3a, 0x80, 0x4e, 0x2e, 0x92, 0x11, 0x2d, 0xe6, 0xd2, 0xd2, 0x6d, 0x6d, 0xb0, 0x8b, 0xff, 0xc4,
	0xce, 0x23, 0x30, 0x4a, 0x06, 0x02, 0x68, 0x8d, 0x4e, 0x8e, 0xfd, 0xd3, 0xa9, 0xb9, 0x53, 0x9e,
	0x27, 0x3e, 0x3e, 0xf7, 0xb1, 0xa9, 0xa1, 0x36, 0xe8, 0x7e, 0x30, 0x31, 0x75, 0xa7, 0x05, 0xc6,
	0x39, 0x4d, 0x63, 0xa7, 0x07, 0xdd, 0x53, 0x8a, 0xc9, 0xfb, 0x82, 0x08, 0xe9, 0x74, 0xa1, 0x5d,
	0x06, 0x2c, 0x5b, 0x3c, 0x3e, 0x84, 0xde, 0xa4, 0x98, 0xbd, 0x25, 0x91, 0xc4, 0x45, 0x46, 0x50,
	0x07, 0x8c, 0x51, 0x70, 0xf6, 0xd2, 0xdc, 0x41, 0x3d, 0x68, 0x4f, 0x83, 0x93, 0xe0, 0x45, 0x89,
	0xf3, 0xc6, 0xd0, 0x67, 0x61, 0xf4, 0x2e, 0x4c, 0x48, 0xdd, 0x8c, 0xee, 0xbb, 0xd5, 0x26, 0xdc,
	0xe5, 0x26, 0xdc, 0x71, 0x9a, 0x91, 0x80, 0xc9, 0x94, 0xce, 0x85, 0xf5, 0xfd, 0x52, 0x57, 0x77,
	0xf9, 0x4b, 0xe5, 0x61, 0xd8, 0x6f, 0x66, 0xce, 0x42, 0x1e, 0xe6, 0x62, 0x0b, 0xed, 0xc7, 0xa5,
	0x6e, 0xeb, 0x83, 0x2e, 0xde, 0xa8, 0xf5, 0x42, 0x40, 0x82, 0xf0, 0x0f, 0x69, 0x44, 0x56, 0x2f,
	0xf2, 0x7f, 0xe2, 0x4f, 0xe5, 0xaf, 0x7f, 0xb4, 0x57, 0x3d, 0xca, 0x8a, 0x10, 0x6f, 0x80, 0x79,
	0xaf, 0x61, 0x2f, 0x27, 0xf2, 0x82, 0xc6, 0x37, 0x9f, 0xf0, 0xeb, 0xdf, 0x13, 0xd6, 0x59, 0xde,
	0x31, 0xf4, 0x9b, 0x63, 0xd1, 0xc3, 0x35, 0xfa, 0xa4, 0x6a, 0x58, 0x0e, 0xf8, 0x7a, 0x55, 0xaf,
	0xb8, 0x29, 0xf4, 0x9e, 0xc3, 0x7e, 0x33, 0x53, 0xaf, 0x78, 0x2b, 0xf0, 0xdb, 0x55, 0xbd, 0xe5,
	0x4d, 0x72, 0x6f, 0x0c, 0xbb, 0x0d, 0xdb, 0xe8, 0xc1, 0x1a, 0xef, 0x99, 0xaa, 0x2f, 0x71, 0x9f,
	0xae, 0x2b, 0x7f, 0x4d, 0x99, 0x87, 0xe1, 0x4e, 0x23, 0x51, 0xbb, 0xdb, 0x46, 0xfb, 0x7c, 0x5d,
	0x99, 0xdb, 0x24, 0x2e, 0xbd, 0x09, 0xc9, 0x49, 0x98, 0x93, 0x58, 0x7d, 0xea, 0xad, 0xb4, 0x2f,
	0xca, 0x5b, 0x07, 0x37, 0x65, 0x4f, 0xef, 0xbd, 0xba, 0x9b, 0xa4, 0xf2, 0xa2, 0x98, 0xb9, 0x11,
	0xcd, 0x87, 0x3c, 0x64, 0x69, 0x9c, 0x51, 0xca, 0x86, 0xe5, 0x0b, 0xce, 0x5a, 0x8a, 0xf5, 0xe4,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x8d, 0x50, 0x86, 0x14, 0x04, 0x00, 0x00,
}
