// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	helloworld.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	HelloFullReply1
	HelloFullReply2
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import nrpc "github.com/rapidloop/nrpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The 'full' version of HelloReply
type HelloFullReply1 struct {
	// Types that are valid to be assigned to Reply:
	//	*HelloFullReply1_Result
	//	*HelloFullReply1_Error
	Reply isHelloFullReply1_Reply `protobuf_oneof:"reply"`
}

func (m *HelloFullReply1) Reset()                    { *m = HelloFullReply1{} }
func (m *HelloFullReply1) String() string            { return proto.CompactTextString(m) }
func (*HelloFullReply1) ProtoMessage()               {}
func (*HelloFullReply1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isHelloFullReply1_Reply interface {
	isHelloFullReply1_Reply()
}

type HelloFullReply1_Result struct {
	Result *HelloReply `protobuf:"bytes,1,opt,name=result,oneof"`
}
type HelloFullReply1_Error struct {
	Error *nrpc.Error `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*HelloFullReply1_Result) isHelloFullReply1_Reply() {}
func (*HelloFullReply1_Error) isHelloFullReply1_Reply()  {}

func (m *HelloFullReply1) GetReply() isHelloFullReply1_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *HelloFullReply1) GetResult() *HelloReply {
	if x, ok := m.GetReply().(*HelloFullReply1_Result); ok {
		return x.Result
	}
	return nil
}

func (m *HelloFullReply1) GetError() *nrpc.Error {
	if x, ok := m.GetReply().(*HelloFullReply1_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HelloFullReply1) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HelloFullReply1_OneofMarshaler, _HelloFullReply1_OneofUnmarshaler, _HelloFullReply1_OneofSizer, []interface{}{
		(*HelloFullReply1_Result)(nil),
		(*HelloFullReply1_Error)(nil),
	}
}

func _HelloFullReply1_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HelloFullReply1)
	// reply
	switch x := m.Reply.(type) {
	case *HelloFullReply1_Result:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Result); err != nil {
			return err
		}
	case *HelloFullReply1_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("HelloFullReply1.Reply has unexpected type %T", x)
	}
	return nil
}

func _HelloFullReply1_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HelloFullReply1)
	switch tag {
	case 1: // reply.result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HelloReply)
		err := b.DecodeMessage(msg)
		m.Reply = &HelloFullReply1_Result{msg}
		return true, err
	case 2: // reply.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(nrpc.Error)
		err := b.DecodeMessage(msg)
		m.Reply = &HelloFullReply1_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _HelloFullReply1_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HelloFullReply1)
	// reply
	switch x := m.Reply.(type) {
	case *HelloFullReply1_Result:
		s := proto.Size(x.Result)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *HelloFullReply1_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// The 'full' version of HelloReply
type HelloFullReply2 struct {
	// Types that are valid to be assigned to Reply:
	//	*HelloFullReply2_Result
	//	*HelloFullReply2_Error
	Reply isHelloFullReply2_Reply `protobuf_oneof:"reply"`
}

func (m *HelloFullReply2) Reset()                    { *m = HelloFullReply2{} }
func (m *HelloFullReply2) String() string            { return proto.CompactTextString(m) }
func (*HelloFullReply2) ProtoMessage()               {}
func (*HelloFullReply2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isHelloFullReply2_Reply interface {
	isHelloFullReply2_Reply()
}

type HelloFullReply2_Result struct {
	Result string `protobuf:"bytes,1,opt,name=result,oneof"`
}
type HelloFullReply2_Error struct {
	Error *nrpc.Error `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*HelloFullReply2_Result) isHelloFullReply2_Reply() {}
func (*HelloFullReply2_Error) isHelloFullReply2_Reply()  {}

func (m *HelloFullReply2) GetReply() isHelloFullReply2_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *HelloFullReply2) GetResult() string {
	if x, ok := m.GetReply().(*HelloFullReply2_Result); ok {
		return x.Result
	}
	return ""
}

func (m *HelloFullReply2) GetError() *nrpc.Error {
	if x, ok := m.GetReply().(*HelloFullReply2_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HelloFullReply2) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HelloFullReply2_OneofMarshaler, _HelloFullReply2_OneofUnmarshaler, _HelloFullReply2_OneofSizer, []interface{}{
		(*HelloFullReply2_Result)(nil),
		(*HelloFullReply2_Error)(nil),
	}
}

func _HelloFullReply2_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HelloFullReply2)
	// reply
	switch x := m.Reply.(type) {
	case *HelloFullReply2_Result:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Result)
	case *HelloFullReply2_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("HelloFullReply2.Reply has unexpected type %T", x)
	}
	return nil
}

func _HelloFullReply2_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HelloFullReply2)
	switch tag {
	case 1: // reply.result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Reply = &HelloFullReply2_Result{x}
		return true, err
	case 2: // reply.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(nrpc.Error)
		err := b.DecodeMessage(msg)
		m.Reply = &HelloFullReply2_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _HelloFullReply2_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HelloFullReply2)
	// reply
	switch x := m.Reply.(type) {
	case *HelloFullReply2_Result:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Result)))
		n += len(x.Result)
	case *HelloFullReply2_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*HelloFullReply1)(nil), "helloworld.HelloFullReply1")
	proto.RegisterType((*HelloFullReply2)(nil), "helloworld.HelloFullReply2")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0x4d, 0x4f, 0xb3, 0x40,
	0x10, 0xc7, 0xe1, 0xc9, 0xd3, 0xd6, 0x4e, 0x4d, 0x34, 0x7b, 0x30, 0xa4, 0xbd, 0x98, 0xd5, 0x18,
	0x4f, 0xa0, 0xf4, 0xe2, 0xc9, 0x03, 0xf1, 0x85, 0x63, 0x83, 0x07, 0xa3, 0x37, 0xda, 0x4e, 0x28,
	0x66, 0xe9, 0x6e, 0x07, 0x88, 0xf6, 0x83, 0xfa, 0x7d, 0xcc, 0x2e, 0x25, 0x50, 0xb5, 0x1e, 0x7a,
	0x21, 0xc3, 0xce, 0xff, 0xff, 0x9b, 0x97, 0x0c, 0x1c, 0x2f, 0x50, 0x08, 0xf9, 0x2e, 0x49, 0xcc,
	0x5d, 0x45, 0xb2, 0x90, 0x0c, 0x9a, 0x97, 0xe1, 0x79, 0x92, 0x16, 0x8b, 0x72, 0xea, 0xce, 0x64,
	0xe6, 0x51, 0xac, 0xd2, 0xb9, 0x90, 0x52, 0x79, 0x4b, 0x52, 0x33, 0xf3, 0xa9, 0x1c, 0x9c, 0xc3,
	0x61, 0xa8, 0x3d, 0x11, 0xae, 0x4a, 0xcc, 0x0b, 0xc6, 0xe0, 0xff, 0x32, 0xce, 0xd0, 0xb1, 0x4f,
	0xed, 0xcb, 0x7e, 0x64, 0x62, 0x7e, 0x01, 0xb0, 0xd1, 0x28, 0xb1, 0x66, 0x0e, 0xf4, 0x32, 0xcc,
	0xf3, 0x38, 0xa9, 0x45, 0xf5, 0x2f, 0x5f, 0xc1, 0x91, 0xd1, 0x3d, 0x94, 0x42, 0x18, 0xed, 0x35,
	0xbb, 0x82, 0x2e, 0x61, 0x5e, 0x8a, 0xc2, 0x68, 0x07, 0xfe, 0x89, 0xdb, 0xea, 0xb9, 0x81, 0x86,
	0x56, 0xb4, 0xd1, 0xb1, 0x33, 0xe8, 0x20, 0x91, 0x24, 0xe7, 0x9f, 0x31, 0x0c, 0x5c, 0xd3, 0xec,
	0xbd, 0x7e, 0x0a, 0xad, 0xa8, 0xca, 0x05, 0x3d, 0xe8, 0x90, 0xf6, 0xf1, 0x97, 0xef, 0x25, 0x7d,
	0xe6, 0x6c, 0x95, 0xec, 0xef, 0x8b, 0xf6, 0x3f, 0x6d, 0xe8, 0x3d, 0x12, 0x62, 0x81, 0xc4, 0x6e,
	0xe1, 0xe0, 0x29, 0x5e, 0x9b, 0x4a, 0xcc, 0xf9, 0x65, 0x04, 0xb3, 0xbb, 0xe1, 0x8e, 0xe1, 0xb8,
	0xc5, 0xee, 0xa0, 0x5f, 0xfb, 0xfd, 0x3f, 0x00, 0xa3, 0x1f, 0x99, 0x66, 0x95, 0xdb, 0x94, 0xf1,
	0x7e, 0x14, 0x9f, 0x5b, 0xc1, 0x1b, 0x8c, 0x52, 0xe9, 0x26, 0x7a, 0x74, 0xfc, 0x88, 0x33, 0x25,
	0x30, 0x6f, 0x19, 0x82, 0x6a, 0x9f, 0xcf, 0x3a, 0x9e, 0xe8, 0x0b, 0x99, 0xd8, 0xaf, 0x37, 0xbb,
	0x2f, 0xa9, 0x26, 0x78, 0x0d, 0xa1, 0x15, 0x4e, 0xbb, 0xe6, 0xc8, 0xc6, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xce, 0x29, 0xb9, 0xa8, 0xaa, 0x02, 0x00, 0x00,
}
